language: node_js
node_js:
- 6
deploy:
  api_key:
    secure: UTLd+sFHV/qXE8VFJ6iJCbLodLg81KQU3tULenJYdKHRQ+Q6QiUTENtOrm1g8CzNFdM6/xvPPXDWCm1CGhqY4zggvl00WrY3MWYFt6lluJ1PQtDsVd7pxicDruFXeoAgeiRmAFlopy5h4+ji+mtlmSoSMuOB8WFjHYS840M8ICZGRkpWF3/821qZSNygt85VlVa5pbVmfv61e04Wupt42C1o/KRGkU13n+XvGQ27THwhLi4k0AU24/n3ocblNKIrfR3JpdSfRIU2q0uABDW5LJ+W0qzyT5CgNQ4VHr9XeV/oTH4wPvdsg7MKUWjCX+ml9Zw89Ja4X5yfGgCPisVMPBQduN+HeRCP/kntjOtb0E+TkKrX44urK1e6akHLbx/0Or1QkYu3I2Q91uSv+vjASxUMGZYz+vJoIbqtk6ig4DPXnUyeh5PfOBDIuCViIJX7DhXXH97YQkaGtcYGMLvheF/AsU5V007e93KsGDOwm4GBnqZzpy3QtT7BmDnNftPoaevonffliyp9Ulm9akDd8P6mKSmyHJJKVL8GB7S0e5OADomPGHa9St1j1jG3H2ZwUHmp2/T5vGPkoc5dQzJgQR8JnJB9s6DbgJwG64fYnUl85Z1aND/QjB3NFTOBwGphzqoFh1nIzQxj6YDCIGoYOSdTcd8+JbAdtabDxOXj7N0=
