language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: tCb1Tt30stquivUfOFc1xT0mhGem47VD4HitHLImEsusbZ5brMmoqJ9P5HMMqkLU4I2MQI95c0LYVO/cV5y9/CEaF0UbNtmKusYb0HKrFzdIK3W8HC7Yox/+cmkQ8Dj7MlIXxy0RkTYEy6hetS2VM0GyKmMwxqPSsCNu+XJo6Hfqygj0zaQm56FluAEI0kAHNN/sXpbZbgV4kA26s8vadBxIw9BmlhKJq18bliVx/qUlgKDq0slmIsBJ2ZAO3yBdPgMTZs5tBfr5m4uZaNFOJyOk43G/MjE05ZnjRB+T440i5XgriItTbMRFF+UbPAJwczFZ3xXB1YENmAKmxMkea85t4SzTSw85NT07Uz9EDpYRwJ2Gz/1L78XL+3wahhVaTpfuowSxXrXkixY2vO5/1sTEideLLqImJj5p9sWcg809GEffz5fJ+KhTQh1HnXdlonxm+qcGomQD9e6PlWJPBiM8ouhiY8kipQiJH86MbCPJWhbrNUu9nNCWHaJ9lY4mDGfI8SktPw2m0fOGDrzxSgs1lqTx9FndqQHoKksZxYxMNMGdFKmu3zxHQBIWQQjkXChQz9keAH1uDwgJZE4aTYLZP8PW3F/pynvDbWT5d+vH1Z3hTTto0q+PjV7trLof/g5Kecnr2xXdw5QNoOamF63DSEK4jd3UigBjNWsMsgg=
